'use strict';

// tests for hello
// Generated by serverless-mocha-plugin

const mod = require('../hello/index.js');
const mochaPlugin = require('serverless-mocha-plugin');

const lambdaWrapper = mochaPlugin.lambdaWrapper;
const expect = mochaPlugin.chai.expect;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'handler' });

describe('hello', () => {
  before((done) => {
//  lambdaWrapper.init(liveFunction); // Run the deployed lambda

    done();
  });

  it('implement tests here', () => {
    return wrapped.run({}).then((response) => {
      const body = JSON.parse(response.body);
      expect(body.message).to.be.equal('the api key is "secret-api-key"');
    });
  });
});
